### ISSUE TITLE
Missing necessary files to use the theme

### ISSUE THREAD

**Issue by ghost** [vietanhdev/geeky-curious#1]
The original theme geeky-hugo had an example site folder in the repo which contained some mock-up content, assests, but most importantly, the `config` directory which has the main configuration files for the site, without which it won't work.

See original theme source here:
[Example Site with Config files](https://github.com/statichunt/geeky-hugo/tree/master/exampleSite)

Can you please add the config files for your version of the theme at least, but ideally also some dummy test content? or maybe the original theme's dummy content would suffice.  But you said you made a lot of changes so your updated config files would be most appreciated.

**Comment by vietanhdev** [comment]
Added exampleSite: <https://github.com/vietanhdev/geeky-curious/commit/39dc545e9a0ce78ab8d983fd410c9d41ce7d682e>.
